# Generated by Django 5.0.4 on 2024-04-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.CharField(default='no image', max_length=122)),
                ('name', models.CharField(default='New Learning Material', max_length=122)),
                ('description', models.TextField(default='New Learning Material')),
                ('file', models.FileField(default='learning_materials/default.pdf', upload_to='learning_materials/')),
            ],
        ),
    ]
