# Generated by Django 5.0.4 on 2024-04-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='cover_image',
            field=models.ImageField(default='learning_materials/default.jpg', upload_to='learning_materials/'),
        ),
    ]
