# Generated by Django 5.0.4 on 2024-04-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_learningmaterial_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='student_number',
            field=models.IntegerField(default=0),
        ),
    ]
