# Generated by Django 5.0.4 on 2024-04-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_learningmaterial_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
