# Generated by Django 5.0.4 on 2024-04-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_learningmaterial_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmaterial',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
