# Generated by Django 5.0.4 on 2024-04-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_learningmaterial_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(default='learning_materials/default.jpg', upload_to='learning_materials/')),
                ('name', models.CharField(default='New Course', max_length=122)),
                ('description', models.TextField(default='New Course')),
                ('student_number', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('materials', models.FileField(default='learning_materials/default.pdf', upload_to='learning_materials/')),
            ],
        ),
        migrations.DeleteModel(
            name='LearningMaterial',
        ),
    ]
