# Generated by Django 5.0.4 on 2024-04-10 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='dataidea', max_length=122)),
                ('email', models.CharField(default='datasideaofficial@gmail.com', max_length=122)),
                ('profile', models.CharField(default='No profile provided', max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New category', max_length=122)),
                ('description', models.CharField(default='New category description', max_length=122)),
                ('color', models.CharField(default='purple', max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='New Blog Slug', max_length=122)),
                ('title', models.CharField(max_length=122)),
                ('cover_image', models.CharField(default='no image', max_length=122)),
                ('popularity', models.FloatField(default=0)),
                ('date_featured', models.CharField(default='no date', max_length=122, null=True)),
                ('content_markdown', models.TextField(default='')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategory')),
            ],
        ),
    ]
