# Generated by Django 5.0.4 on 2024-04-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_date_alter_blog_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='profile.jpg', upload_to='author_images/'),
            preserve_default=False,
        ),
    ]
